services:
  - type: web
    name: story-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: COHERE_API_KEY
        sync: false
